# Generated by Django 5.2.3 on 2025-06-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('cost_per_day', models.FloatField()),
                ('all_inclusive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_app.people')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_app.room')),
            ],
        ),
    ]
